const cors = require('cors')
const express = require('express')
const app = new express()
const path = require('path')
require('dotenv').config()
require(path.join(__dirname, './model/mongoose'))
require(path.join(__dirname, './database/config'))
const messagesroute = require(path.join(__dirname, './routes/messages'))
const blogroute = require(path.join(__dirname, './routes/blog'))
const alumniroute = require(path.join(__dirname, './routes/alumni'))
const post_bearer = require(path.join(__dirname, './routes/post_bearer'))

app.use(express.static(path.join(__dirname,'../client/build/')))
    .use('/api', messagesroute)
    .use('/api', blogroute)
    .use('/api', alumniroute)
    .use('/api',post_bearer)
    .use(express.json())
    .use(cors())
    .get('*', (req, res) =>
        res
            .status(200)
            .sendFile('index.html')
    )
    .listen(5005,()=>console.log('http://localhost:5005'))